### ISSUE TITLE
Is there some Annotation information abou pangenomeMTB_consensus.fasta?

### ISSUE THREAD

**Issue by Dx-wmc** [cvn001/transflow#1]
Hello, 

a question was raised when I was using your pipeline. Usually, when we use h37rv or other reference genomes, there are annotation files in gff or Genbank format, but the pangenomeMTB_consensus.fasta used in this pipeline does not contain this. Could you add some annotation information on pangenomeMTB_consensus.fasta? 

In addition, a lot of SNPs files are generated using gatk. Which file should we employ in the end?

Best regards,

Dave

**Comment by cvn001** [comment]
Hi,

currently, there is no annotation information for this pangenome sequence (pangenomeMTB_consensus.fasta). This reference sequence is only used for SNP detection and SNP-distance analysis, and cannot be used for SNP annotation and drug resistance-related prediction like the H37Rv genome as reference.  

This workflow uses the ***_vars_snps.vcf** file for calculating SNP differences, sorry for not removing many irrelevant files.

Best,

Xiangchen Li

**Comment by Dx-wmc** [comment]
> Hi,
> 
> currently, there is no annotation information for this pangenome sequence (pangenomeMTB_consensus.fasta). This reference sequence is only used for SNP detection and SNP-distance analysis, and cannot be used for SNP annotation and drug resistance-related prediction like the H37Rv genome as reference.
> 
> This workflow uses the ***_vars_snps.vcf** file for calculating SNP differences, sorry for not removing many irrelevant files.
> 
> Best,
> 
> Xiangchen Li

Thank you for your answer!

Dave
