### ISSUE TITLE
fastq files not going to temp file

### ISSUE THREAD

**Issue by ghost** [cvn001/transflow#3]
Good morning. When the snakemake file executes, the .fastq.gz files are not loading into the tmp/directory. Any advice on this issue?

![image](https://github.com/cvn001/transflow/assets/91744154/e8232bd0-72bb-4e17-832d-df85f622c551)

**Comment by ghost** [comment]
Hello...this is the downstream effect of the above error.

![image](https://github.com/cvn001/transflow/assets/91744154/084228b7-64f8-4ad4-a152-29e6cdb54b7e)

**Comment by ghost** [comment]
Got it working....looking forward to using this program!

**Comment by Czirion** [comment]
Dear @bdelavan,

I am having a similar issue. How did you solve it?

Thanks
