### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by Czirion** [cvn001/transflow#5]
Hello,

I installed Transflow using Mamba and cannot run the example. It only produced the FastQC outputs for S5 and S8

I ran the next code from the `transflow/` directory:
`bash transflow.sh --configfile config/configfile.yaml --cores 4 --verbose`

The first warning message that I get is:
 `miniconda3/envs/transflow/lib/python3.10/site-packages/google/protobuf/internal/api_implementation.py:110: UserWarning: Selected implementation cpp is not available.
  warnings.warn(`

I attach the complete log file [transflow_example.log](https://github.com/cvn001/transflow/files/11618160/transflow_example.log)

Note: I am running it in a SLURM-based cluster and I have the conda environment in one user but I cloned the repository and ran the workflow from another user.

Please let me know if you need any more information.

Thank you,

Claudia

**Comment by cvn001** [comment]
Hi Claudia,

Thanks for your interest in our pipeline.

Unfortunately we did not test TransFlow on a Slurm-based cluster. 

According to the [Snakemake manual](https://snakemake.readthedocs.io/en/stable/executing/cluster.html#cluster-slurm), Snakemake provides a specific support for Slurm. Please re-run transflow.sh and add execution parameters related to Slurm.

Best,

Xiangchen Li

**Comment by Czirion** [comment]
Dear Xiangchen Li,

Thank you for quick your response.

I was not able to run it using the Slurm parameters `--slum `--jobs 1`.

But I persevered in making the installation with Conda instead of Mamba, and now it works fine, so it was an issue with the Mamba installation and not related to Slurm.

Thank you!

All the best,

Claudia
